spring.datasource.url=jdbc:postgresql://localhost:5432/Student_Manager_System
spring.datasource.username=postgres
spring.datasource.password=Postgres@1703
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true